// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = Controller(function() {
    'use strict';
    return {
      init: function(http) {
        return this["super"]('init', http);
      }
    };
  });

}).call(this);

//# sourceMappingURL=BaseController.js.js.map
