// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  module.exports = Controller("Milk/BaseController", function() {
    return {
      indexAction: function() {
        return this.display();
      }
    };
  });

}).call(this);

//# sourceMappingURL=IndexController.js.map
