// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      cssmin: {
        options: {
          shorthandCompacting: false,
          roundingPrecision: -1
        },
        target: {
          files: {
            './www/resource/dist/vendor.min.css': ['./www/resource/stylesheet/common.css', './www/resource/stylesheet/style.css']
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    return grunt.registerTask('default', ['cssmin']);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
