// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = Controller(function() {
    'use strict';
    return {
      init: function(http) {
        var self;
        this["super"]('init', http);
        self = this;
        D('article_cat').query('select *,(select COUNT(0) from that_article where that_article_cat.cid=that_article.cat) as len from that_article_cat').then(function(data) {
          self.assign({
            catList: data,
            thisCId: parseInt(http.get['cid'] || http.post['cid'])
          });
          return self.fetch('chips/index_cat_list.html').then(function(content) {
            self.catListContent = content;
            return self.assign({
              catListContent: content
            });
          });
        });
        return self.session('memberInfo').then(function(s) {
          if (!isEmpty(s)) {
            return self.assign('user', {
              name: s.name,
              id: s.mid
            });
          } else {
            return self.assign('user', {});
          }
        });
      },
      __before: function(action) {
        return this.assign({
          title: action,
          module: action,
          scriptActive: true
        });
      }
    };
  });

}).call(this);

//# sourceMappingURL=BaseController.js.map
