// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = Controller(function() {
    'use strict';
    return {
      init: function(http) {
        var self;
        this["super"]('init', http);
        self = this;
        return D('article_cat').select().then(function(data) {
          self.assign({
            catList: data,
            thisCId: parseInt(http.get['cid'] || http.post['cid'])
          });
          return self.fetch('chips/index_cat_list.html').then(function(content) {
            self.catListContent = content;
            return self.assign({
              catListContent: content
            });
          });
        });
      },
      __before: function(action) {
        return this.assign({
          title: action,
          module: action,
          scriptActive: true
        });
      }
    };
  });

}).call(this);

//# sourceMappingURL=BaseController.js.map
